### ISSUE TITLE
Empty documentation repository

### ISSUE THREAD

**Issue by dowlingw** [awsdocs/aws-config-developer-guide#1]
**Expected Behaviour:**
Documentation to be present in the repository so customers can submit pull requests.

**Actual Behaviour:**
Empty repository.

**Notes:**
Okay, I realise this is fairly obvious - but I'm about to lodge an issue for some documentation feedback and file a PR with resolution.

But it looks like this repository hasn't been populated yet, maybe it's an oversight or still in progress.

Just wanted to report it and give it a nudge!

**Comment by PatMyron** [comment]
@jamesiri @hyandell @joshbean @jpeddicord any update on this?

https://github.com/awsdocs/aws-robomaker-developer-guide/issues/2

All of these [awsdocs](http://github.com/awsdocs/) repositories are empty:

https://github.com/awsdocs/aws-iot-sitewise-api-docs
https://github.com/awsdocs/aws-iot-sitewise-user-guide
https://github.com/awsdocs/mxnet-on-aws-developer-guide
https://github.com/awsdocs/amazon-machinelearning-developer-guide
https://github.com/awsdocs/aws-robomaker-developer-guide
https://github.com/awsdocs/aws-config-developer-guide

**Comment by joshbean** [comment]
Hi Pat,

Somehow I completely missed this! Sorry for the ridiculous delay. I'm adding a few more folks to the discussion.

@AwsKarlito for IOT SiteWise
@aaronmarkham for MXNet on AWS
@BrentKellmer for Machine Learning
@ebattalio for RoboMaker
@AWSShubhangiV for Config

Folks - can we get those repos populated with the Markdown documentation files?

**Comment by aaronmarkham** [comment]
I updated the README for MXNet - there are no docs, so I'm just pointing people to the MXNet website.

**Comment by AWSShubhangiV** [comment]
Docs are live.
