### ISSUE TITLE
Doc Error - Section Setting Up Auto Remediation (Console)

### ISSUE THREAD

**Issue by IronCore864** [awsdocs/aws-config-developer-guide#10]
Section `Setting Up Auto Remediation (Console), step 3:

> On the Edit name of the rule page, in the Choose remediation action section, choose the appropriate remediation action from the recommended list.

This is not correct anymore.

The right step would be something like:

> Select an existing rule, click the "Actions" dropdown menu, then choose "Manage remediation".

**Comment by dafolabi** [comment]
Thank you for pointing this out! The documentation has been updated 👍

**Comment by IronCore864** [comment]
Kudos on that! Very fast response and the change is already live.
