### ISSUE TITLE
Improvement: Include all currently available AWS::Logs::* and AWS::CloudWatch::* in "Supported Resource Types"

### ISSUE THREAD

**Issue by Risae** [awsdocs/aws-config-developer-guide#19]
Hi,

could you add these resources to the list of "Supported Resource Types" of CloudWatch and describe wether or not they are supported by AWS Config?:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_CloudWatch.html
AWS::CloudWatch::Alarm (already listed)
AWS::CloudWatch::AnomalyDetector
AWS::CloudWatch::CompositeAlarm
AWS::CloudWatch::Dashboard
AWS::CloudWatch::InsightRule
AWS::CloudWatch::MetricStream

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Logs.html
AWS::Logs::Destination
AWS::Logs::LogGroup
AWS::Logs::LogStream
AWS::Logs::MetricFilter
AWS::Logs::QueryDefinition
AWS::Logs::ResourcePolicy
AWS::Logs::SubscriptionFilter

**Comment by dafolabi** [comment]
Thank you for your comment. If a resource type is not listed in the Supported Resource Types page (https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html), then it is not currently supported by AWS Config.

As you noted, currently the only supported resource type among the ones you mentioned is AWS::CloudWatch::Alarm (https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html#amazoncloudwatch).
