### ISSUE TITLE
Update Operational Best Practices for FFIEC > Control ID - D1.G.RM.Rm.1

### ISSUE THREAD

**Issue by vkumbha** [awsdocs/aws-config-developer-guide#21]
Thanks for the great [document](https://docs.aws.amazon.com/config/latest/developerguide/operational-best-practices-for-ffiec.html) on Operational Best Practices for FFIEC, which is of great help and gives a good understanding of governing our AWS Accounts better.
We at [Steampipe](https://steampipe.io/) are relying on this to build compliance [mod](https://hub.steampipe.io/mods?objectives=compliance) for FFIEC. While I was going through the FFIEC document to understand more about this, I did notice a small deviation in the Control ID for `D1.G.RM.Rm.1`

I believe the Control IDs in the document follow the pattern "Domain > Assessment Factor > Component > Maturity Level > Declarative Statement". Below is a screenshot from the FFIEC documentation which talks about the bits and pieces in the document.
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/40973863/174961220-d0b1ee54-6553-45e6-92b0-0f8a07e482cd.png">

For example: 
The below screenshot talks about the declarative statement from "Domain1 > Training and Culture > Training > Baseline > 2" ```Annual information security training includes incident response, current cyber threats (e.g., phishing, spear phishing, social engineering, and mobile security), and emerging issues.``` The Control ID for this corresponds to **`D1.TC.Tr.B.2`.**
<img width="757" alt="image" src="https://user-images.githubusercontent.com/40973863/174978351-be95f1ef-df81-47fb-82e3-7cf6661e39d5.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/40973863/174981276-918cc8a5-0d6b-4522-ac2e-0ebc018c0bb3.png">

Likewise, I believe the baseline "Domain 1 > Risk Management > Risk Management Program > Baseline > 1" should have the Control Id as `D1.RM.Rm.B.1` and not `D1.G.RM.Rm.1`
<img width="856" alt="image" src="https://user-images.githubusercontent.com/40973863/174960956-2b4c7843-93cc-4b7e-a32a-b0931759c4ea.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/40973863/174981579-903a785c-cd21-4fc7-ab32-4a33741693ee.png">

Also, the "Control Description" for **D2.TI.Ti.B.3** should be `Threat information is used to enhance internal risk management and controls.` and not `Threat information is used to monitor threats and vulnerabilities.`

I could be wrong in my approach as well, happy to learn and understand the deviation in naming the Control Id as `D1.G.RM.Rm.1`. Let me know if you need any more information. Thank you!

**Comment by dafolabi** [comment]
Thanks for the feedback! The [documentation](https://docs.aws.amazon.com/config/latest/developerguide/operational-best-practices-for-ffiec.html) has been updated 👍

**Comment by vkumbha** [comment]
@dafolabi Thanks for updating the control description for ` D2.TI.Ti.B.3`. However, I do not see the control ID change for `D1.G.RM.Rm.1`, I believe it has to be `D1.RM.Rm.B.1 `.

**Comment by dafolabi** [comment]
Thanks for calling that out! Part of the update was delayed. The mapping table should now be fully updated
