### ISSUE TITLE
Where to find AWS Config newly supported 15 new resource type rules?

### ISSUE THREAD

**Issue by rajlearner17** [awsdocs/aws-config-developer-guide#22]
Hi Team
We see the latest resource type support in AWS config [here](https://aws.amazon.com/about-aws/whats-new/2022/06/aws-config-15-new-resource-types/)

Should we expect this list to be updated below and the respective config rule support available in the AWS Config console?
https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html

Or I am missing checking some other document?

Thanks in advance!

**Comment by dafolabi** [comment]
Thanks for your comment! You can find the list of supported resource types here: https://docs.aws.amazon.com/config/latest/developerguide/resource-config-reference.html the AWS Config console should also display the new resource types and be regarded as the source of truth for what resource types are available in your region
