### ISSUE TITLE
[EC2.21] nacl-no-unrestricted-ssh-rdp 

### ISSUE THREAD

**Issue by schwichti** [awsdocs/aws-config-developer-guide#25]
Hi, 
consider this rule here:
https://github.com/awsdocs/aws-config-developer-guide/blob/main/doc_source/nacl-no-unrestricted-ssh-rdp.md

> This control checks whether a network access control list (NACL) allows unrestricted access to the default ports for SSH/RDP ingress 
> traffic. The rule fails if a NACL inbound entry allows a source CIDR block of '0.0.0.0/0' or '::/0' for ports 22 or 3389.

In order to satisfy this rule it seems that there must not be any rule in the ACL (disregarding its priority) that allows SSH/RDP.
I suggest allowing explicit denial of traffic on port 22, 3389 to satisfy this rule

Instead of this:
| rule number | type        | protocol | port range | allow/deny |
|-------------|-------------|----------|------------|------------|
| 10          | All traffic | All      | 0,21       | allow      |
| 20          | All traffic | All      | 23, 3388    | allow      |
| 30          | All traffic | All      | 3390, 65536       | allow      |

Also allow this to satisfy the rule
| rule number | type        | protocol | port range | allow/deny |
|-------------|-------------|----------|------------|------------|
| 10          | Custom TCP | TCP      | 22       | deny      |
| 20          | Custom TCP | TCP      | 3388       | deny      |
| 30          | All traffic | All      | 0, 65536       | allow      |

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
