### ISSUE TITLE
Conformance Packs do not exclude GovCloud from region

### ISSUE THREAD

**Issue by Adam-Zvolanek** [awsdocs/aws-config-developer-guide#27]
For example, on line 7 of https://github.com/awsdocs/aws-config-developer-guide/blob/main/doc_source/operational-best-practices-for-nist-800-53_rev_5.md the text should be amended to read:

**AWS Region:** All supported AWS Regions except Middle East \(Bahrain\) and AWS GovCloud (US).

The lack of exclusionary notes throughout conformance packs makes it seem to those non-technical that conformance packs are available in a GovCloud environment. Likewise, best-practice conformance pack pages including the one linked above, specifically excludes me-south-1 while being listed as 'region support' on the [Conformance Packs](https://docs.aws.amazon.com/config/latest/developerguide/conformance-packs.html) page.

Added consistency and transparency in noting conformance packs are **not** available in GovCloud needs to be noted.

**Comment by dafolabi** [comment]
The documentation has been updated
