### ISSUE TITLE
Improvement: Clarify approved-amis-by-tag input parameter example

### ISSUE THREAD

**Issue by seporaitis** [awsdocs/aws-config-developer-guide#4]
**Problem:**

[Documentation](https://docs.aws.amazon.com/config/latest/developerguide/approved-amis-by-tag.html) for `amisByTagKeyAndValue` parameter in `approved-amis-by-tag` rule is very ambiguous when it comes to multiple values of the same tag or multiple tags:

> The AMIs by tag (comma-separated list up to 10; for example, "tag-key:tag-value").

At a straightforward interpretation of the above this implies that for multiple values of the same tag this should work: `tag1:value1,tag2:value2`, but it does not.

**Suggested Resolution:**

The example in documentation could be more extensive:

> The AMIs by tag (comma-separated list up to 10; for example, "tag-key1,'tag-key2:value1,value2',tag-key3:value3" would match AMIs with tag-key1 or tag-key2 having values value1 or value2, or tag-key3 with value3).

**Commentary:**

I couldn't find if there is any other, more extensive, examples for this config rule, but I think it would save users time debugging the issue or waiting for an explanation from support.

Note, english is a second language to me so suggested resolution text above should be proofread.

**Comment by AWSShubhangiV** [comment]
Updated documentation.
