### ISSUE TITLE
Improvement: Update required permissions when using service-linked roles

### ISSUE THREAD

**Issue by seporaitis** [awsdocs/aws-config-developer-guide#5]
**Problem:**

Currently the [documentation](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-policy.html#required-permissions-using-servicelinkedrole) suggests this bucket policy when using AWS Config with service-linked roles:

```lang=json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AWSConfigBucketPermissionsCheck",
      "Effect": "Allow",
      "Principal": {
        "Service": [
         "config.amazonaws.com"
        ]
      },
      "Action": "s3:GetBucketAcl",
      "Resource": "arn:aws:s3:::targetBucketName"
    },
    {
      "Sid": " AWSConfigBucketDelivery",
      "Effect": "Allow",
      "Principal": {
        "Service": [
         "config.amazonaws.com"    
        ]
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::targetBucketName/[optional] prefix/AWSLogs/sourceAccountID-WithoutHyphens/Config/*",
      "Condition": { 
        "StringEquals": { 
          "s3:x-amz-acl": "bucket-owner-full-control" 
        }
      }
    }
  ]
}   
```

However, AWS Config had a change recently, where it also needs to check which region the bucket was created in. The above policy does not take that into consideration and accounts that have alerts set-up for unauthorized access attempts see a lot of noise generated by AWS Config.

**Suggested resolution:**

As recommended by AWS Premium Support representative, an additional `s3:ListBucket` permission is now required for the alerts to stop. It would be good to adjust the documentation accordingly:

```lang=json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AWSConfigBucketPermissionsCheck",
      "Effect": "Allow",
      "Principal": {
        "Service": [
         "config.amazonaws.com"
        ]
      },
      "Action": [
        "s3:GetBucketAcl",
        "s3:ListBucket"   # <-- NEW PERMISSION
      ],
      "Resource": "arn:aws:s3:::targetBucketName"
    },
    {
      "Sid": " AWSConfigBucketDelivery",
      "Effect": "Allow",
      "Principal": {
        "Service": [
         "config.amazonaws.com"    
        ]
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::targetBucketName/[optional] prefix/AWSLogs/sourceAccountID-WithoutHyphens/Config/*",
      "Condition": { 
        "StringEquals": { 
          "s3:x-amz-acl": "bucket-owner-full-control" 
        }
      }
    }
  ]
}   
```

**Commentary:**

When not enabled this causes `AccessDenied` errors with `HeadBucket` as `eventName`. Trying to add `s3:HeadBucket` as permission to bucket policy fails validation and thus is not possible. It is therefore hard to make a link that to fix `HeadBucket` - `ListBucket` permission is needed, unless told by AWS Support. 

Assuming that whoever can action this can also see AWS support cases - I can provide an AWS Premium Support case number that has more context.

**Comment by MattMCloudy** [comment]
@seporaitis You should be able to see the updates to [the documentation](https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-policy.html#required-permissions-using-servicelinkedrole) which include the `AWSConfigBucketExistenceCheck` permission. Including this permission should resolve the `AccessDenied` errors that you are seeing.

**Comment by seporaitis** [comment]
Thank you!
